### ISSUE TITLE
The plugin conflicts with the CardBoard plugin.

### ISSUE THREAD

**Issue by alexguo78** [oxdc/obsidian-vertical-tabs#21] opened 2024-08-17 14:46 UTC
<img width="540" alt="截屏2024-08-17 22 40 30" src="https://github.com/user-attachments/assets/fc22b6e5-f8b3-482a-8df5-eddc482f9774">
After enabling the plugin, the tabs in the CardBoard plugin also disappear.

**Comment by oxdc** [comment] 2024-08-17 16:39
That's weird 🐛 Probably some CSS issue. I'll look into it ASAP.

**Comment by oxdc** [comment] 2024-08-18 11:34
Conflicts are now resolved, please upgrade to the latest version. If you find any problems, please reopen this issue or open a new one.

**Comment by alexguo78** [comment] 2024-08-18 13:55
I am very pleased to be able to use your plugin; it has brought me great convenience. Thank you.

The version has already been updated to 0.6.5, but the tab effects in the CardBoard plugin are as follows:
Before enabling:
[cid:a37e2a21-65a1-4495-8c38-700d0b4c47df]
After enabling:
[cid:944ce616-95d9-4163-ad34-b1948e74e6a5]
________________________________
发件人: oxdc ***@***.***>
发送时间: 2024年8月18日 19:35
收件人: oxdc/obsidian-vertical-tabs ***@***.***>
抄送: alexguo78 ***@***.***>; Author ***@***.***>
主题: Re: [oxdc/obsidian-vertical-tabs] The plugin conflicts with the CardBoard plugin. (Issue #21)


Conflicts are now resolved, please upgrade to the latest version. If you find problems, please reopen this issue or open a new one.

―

**Comment by oxdc** [comment] 2024-08-18 14:46
I’m sorry for any trouble this has caused. The images, however, are broken. Could you please upload them directly from GitHub?

**Comment by alexguo78** [comment] 2024-08-18 22:10
Before enabling:
![Uploading thumbnail_截屏2024-08-18 21.44.10.png…]()

After enabling:
![Uploading thumbnail_截屏2024-08-18 21.43.44.png…]()

**Comment by alexguo78** [comment] 2024-08-18 22:11
Before enabling:
<img width="467" alt="1" src="https://github.com/user-attachments/assets/fee74580-eb07-4250-a131-07f2ea921a14">


After enabling:
<img width="398" alt="3" src="https://github.com/user-attachments/assets/0b2cf175-fb8a-4189-b62c-d8d4ad5595ad">

**Comment by oxdc** [comment] 2024-09-01 07:04
Sorry for the late reply. I could not reproduce the bug with the latest version of both plugins. Could you please upgrade both plugins and reopen Obsidian? If the problem persists, please try to reproduce it in the Sandbox vault. I shall close this issue right now. If things still won't work, please reopen this issue. Thank you.

**Closed by oxdc** 2024-09-01 07:04 UTC
Labels: bug, enhancement
