### ISSUE TITLE
Performance issue of Drag and Drop

### ISSUE THREAD

**Issue by ifulou** [oxdc/obsidian-vertical-tabs#55] opened 2024-11-05 14:54 UTC
See the picture.
![Vertical tab bug](https://github.com/user-attachments/assets/38c77f34-f6a8-4919-a81d-f332ef01c6e0)

**Comment by oxdc** [comment] 2024-11-05 15:57
Thank you for reporting the problem. Since I cannot reproduce on my side, I need further information.

It seems that you are drag&drop files in Obsidian's native File Browser, not in *Vertical Tabs*. May I ask if this issue exists in *Vertical Tabs*? And could you please disable all CSS snippets and switch to the default theme temporarily and see if the problem still happens?

**Comment by spiritualgeek** [comment] 2024-11-06 06:02
Hi @oxdc 

I love the plugin but have the same issue.

I went through plugin by plugin and when I switched off Vertical Tabs the issue went away

As per the above, this is in the native file browser

Thanks

**Comment by spiritualgeek** [comment] 2024-11-06 15:15
Can do so tomorrow if time permits. My main driver presently is an M1 Studio with 32GB of RAM - Not that old :)

**Comment by oxdc** [comment] 2024-11-06 15:24
@spiritualgeek Thank you!

> Can do so tomorrow if time permits.

That's great! Thank you again!

> M1 Studio with 32GB of RAM

Whoa that's not what I expected 🤣 I will try to reproduce this on my own.

**Comment by oxdc** [comment] 2024-11-11 13:21
Hi @ifulou @spiritualgeek ! The latest version includes a fix that *might* resolve this performance issue. Please upgrade and test. Thank you!

**Comment by spiritualgeek** [comment] 2024-11-12 05:40
I appreciate the feedback, but I started using a feature of Another Quick Switcher that I was not before, so I'm no longer using V-Tabs

Note someone on discord is reporting the same - https://discord.com/channels/686053708261228577/694233507500916796/1305653312653099111

I may return to using it in future :)

**Comment by oxdc** [comment] 2024-11-12 13:03
Hi @spiritualgeek ! Thank you for providing useful information. I'll try to fix this issue.

**Comment by Bigmanvst** [comment] 2024-11-13 18:27
Hi,
Great plugin, thanks a lot.
But I keep just your plugin installed, and I have this lag.
I have Macos / M3 pro, I deactivated for the moment until the update / fix.
Thanks
Regards.

**Comment by oxdc** [comment] 2024-11-14 02:57
Hi @Bigmanvst ! I know this is frustrating. I'm trying very hard to find the cause and get this fixed. This is the first priority now. May I ask if you have time to help me debugging? I desperately need some feedback and useful information from someone who has this issue. Thanks!

**Comment by oxdc** [comment] 2024-11-22 08:50
Hi everyone! Some updates on this issue: I can only reproduce it under some extreme conditions. I got access to an old PC and opened about fifty tabs. After few clicks in the file browser, I tried to move a file to some folder, the lag happened, but the issue disappeared a few seconds later. My observation is that: when you try to drag and drop a file, Obsidian makes the file browser into focus (or active), which triggers the “active-leaf-changed” event. *Vertical Tabs* then get notified to make some updates, which triggers a full rerender of the vertical tab list. While this process is resource demanding and happens immediately when you click and drag the file, there might not be enough CPU power for the render process, thus producing the lag.

For anyone who wants to help me fix this bug, all you need to do is a few seconds and clicks! Please read the instructions:

- Open your vault and close all private notes (performance recording automatically records your screen, this is to make sure you don't accidentally share some sensitive information);
- Install and enable _Vertical Tabs_ (if you haven't);
- Open the Dev Console by pressing  cmd+option+I on MacOS or ctrl+shift+I on Windows;
- Navigate to the "Performance" tab in the Dev Console;
- Click the "Record" button;
- Try to reproduce the bug, let it happen for a few seconds.
- Click the "Stop" button;
- Click the "Download" button and save the file;
- Post the saved file here or leave a message to send it to me privately.

Thank you for your help!

The official guide on recording can be found [in the section "Record runtime performance" here](https://developer.chrome.com/docs/devtools/performance#record).

**Comment by bakebakebakebake** [comment] 2024-12-04 14:06
> Hi everyone! Some updates:
> 
> The lag is caused by CSS recalculation micro tasks fired when drag&drop files. These tasks are fired even without _Vertical Tabs_ installed, probably to be some design issue of Obsidian. When you use some complex themes or CSS snippets, these micro tasks will take up a huge amount of CPU power. Besides, _Vertical Tabs_ needs to update the states at the same time, since the focus has moved to the File Browser, which causes the appearance of the lag.

However, my theme is minimal and I haven't used any CSS snippets, but I still encountered this issue. It manifests as slow animation when dragging. When I remove this plugin, the problem disappears.

Additionally, there are some other issues:

1. Sometimes there is a lag when using your plugin, and I'm not sure of the reason (my computer's configuration is not low).
2. When simultaneously operating on Obsidian's native page and Vertical Tabs, there are some problems: it seems to only switch the last group, which significantly affects the experience.

**Comment by oxdc** [comment] 2024-12-05 04:12
Hi everyone here! *Vertical Tabs* will no longer update its states when files are dragged and dropped using the native file browser. Please update to v0.11.2 to test. More performance enhancements are on the way in the coming weeks—stay tuned! 🚀

**Comment by bakebakebakebake** [comment] 2024-12-05 05:57
> > 1. Sometimes there is a lag when using your plugin, and I'm not sure of the reason (my computer's configuration is not low).有时使用你的插件时会出现延迟，我不确定原因（我的电脑配置不低）。
> 
> Hi @bakebakebakebake ! Could you please make a performance record by following the steps above?你好！您能否按照上述步骤制作性能记录？
> 
> > 2. When simultaneously operating on Obsidian's native page and Vertical Tabs, there are some problems: it seems to only switch the last group, which significantly affects the experience.同时在 Obsidian 的原生页面和 Vertical Tabs 上操作时，存在一些问题：似乎只切换了最后一组，这显着影响了体验。
> 
> Could you please attach a screenshot or recording? I am afraid that I did not understand your problem. Thank you!您能否附上屏幕截图或录音？恐怕我没有理解你的问题。谢谢！

I took a screenshot, not sure if it is useful.

![image](https://github.com/user-attachments/assets/b8e2b4c1-7c10-4a94-af57-28226eb46e23)

**Comment by bakebakebakebake** [comment] 2024-12-05 06:05
> > 1. Sometimes there is a lag when using your plugin, and I'm not sure of the reason (my computer's configuration is not low).
> 
> Hi @bakebakebakebake ! Could you please make a performance record by following the steps above?
> 
> > 2. When simultaneously operating on Obsidian's native page and Vertical Tabs, there are some problems: it seems to only switch the last group, which significantly affects the experience.
> 
> Could you please attach a screenshot or recording? I am afraid that I did not understand your problem. Thank you!

When vertical tabs are enabled:

https://github.com/user-attachments/assets/26135ae8-2861-40e1-982b-c5edac636532

When vertical tabs are disabled:

https://github.com/user-attachments/assets/57674efc-d243-4acb-be2f-a72000f5e308

I am certain that there is an issue with this plugin. If this issue is resolved, I believe the plugin will be excellent.

**Comment by oxdc** [comment] 2024-12-05 06:23
Hi @bakebakebakebake ! Does the problem persist in the latest version v0.11.2? Please note that you have to close and reopen Obsidian after the update.

**Comment by bakebakebakebake** [comment] 2024-12-05 06:27
> Hi @bakebakebakebake ! Does the problem persist in the latest version v0.11.2? Please note that you have to close and reopen Obsidian after the update.

Yes, I have tested it again after updating.

**Comment by oxdc** [comment] 2024-12-05 06:31
@bakebakebakebake This is super weird. Could you please provide the debug info by following [the official guide](https://help.obsidian.md/Help+and+support#Collect+debug+information)?

**Comment by bakebakebakebake** [comment] 2024-12-05 06:37
> @bakebakebakebake This is super weird. Could you please provide the debug info by following [the official guide](https://help.obsidian.md/Help+and+support#Collect+debug+information)?

Sure.Here is:

SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.4.16
	Operating system: Windows 10 Pro for Workstations 10.0.22631
	Login status: logged in
	Language: zh
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.4.7
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 23
	Plugins enabled: 17
		1: Auto Link Title v1.4.1
		2: Calendar v1.5.10
		3: Easy Typing v5.1.10
		4: Go to Line v0.0.2
		5: Latex Suite v1.8.9
		6: Colored Text v0.6.0
		7: Mousewheel Image zoom v1.0.19
		8: Minimal Theme Settings v7.3.1
		9: Style Settings v1.0.7
		10: Regex Find/Replace v1.2.0
		11: Hider v1.3.1
		12: Better Export PDF v1.8.0
		13: Customizable Menu v2.2.0
		14: Hover Editor v0.11.15
		15: Git v2.24.3
		16: Remotely Save v0.5.25
		17: Vertical Tabs v0.11.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by oxdc** [comment] 2024-12-05 10:07
Hi @bakebakebakebake ! I cannot reproduce with exactly the same configuration as you posted. But I do find a clue [here](https://forum.obsidian.md/t/freezes-stutters-style-recalculation-while-scrolling-a-page-that-embeds-a-page-with-many-embeds/67183), someone reported the same issue without using *Vertical Tabs*. May I ask: do you have open notes with embed links `![[ ]]` ? I can only reproduce when a note with embedded links is open.

**Comment by oxdc** [comment] 2024-12-05 10:18
Update: seem to be something wrong with DropIndicator CSS of *Vertical Tabs*.

**Comment by oxdc** [comment] 2024-12-05 10:42
Hi @bakebakebakebake and everyone else! Could you please update to v0.11.3? I published a hot fix on CSS.

**Comment by bakebakebakebake** [comment] 2024-12-05 10:46
> Hi @bakebakebakebake and everyone else! Could you please update to v0.11.3? I published a hot fix on CSS.

The issue has been perfectly resolved and it is running smoothly!😀👍🏼

**Comment by oxdc** [comment] 2024-12-09 04:54
Hi @ifulou @spiritualgeek and @Bigmanvst !

Thank you for bringing this performance issue to my attention! The issue should now be resolved, so I’ll close it and mark it as complete. If you continue to experience performance lags after updating to the latest version (v0.11.3), please don’t hesitate to reopen the issue. As always, please remember to restart Obsidian after updating.

**Closed by oxdc** 2024-12-09 04:54 UTC
Labels: bug
