### ISSUE TITLE
Hotkey for zen mode gone in 0.6.10?

### ISSUE THREAD

**Issue by n-konig** [oxdc/obsidian-vertical-tabs#38] opened 2024-09-23 12:32 UTC
It seems to me that after install of 0.6.10 (Obsidian version 1.7.2, Windows), the only command available for hotkeys is "open vertical tabs" - zen mode is no longer available!

![image](https://github.com/user-attachments/assets/b303d9aa-9b79-4a9a-9bb9-3d1b529d4649)

**Comment by oxdc** [comment] 2024-09-23 14:32
Could you please try to reproduce this issue in the Sandbox Vault? Since everything works fine for me, I'm not sure if reopening Obsidian would help (which is mandatory after upgrading to v0.6.10).

**Comment by n-konig** [comment] 2024-09-23 15:09
Uninstalled and reinstalled the plugin, and everything is restored 😅.
Sorry for the false alarm.
And thanks for the great plugin!
/Niclas

**Comment by oxdc** [comment] 2024-09-25 14:39
You are welcome! I'll close this issue right now. In case things go wrong again, you may reopen it.

**Closed by oxdc** 2024-09-25 14:39 UTC
Labels: help wanted
