### ISSUE TITLE
Middle mouse to close tab

### ISSUE THREAD

**Issue by Moyf** [oxdc/obsidian-vertical-tabs#14] opened 2024-08-12 15:23 UTC
Just like in most browsers, it would be really nice to  be able to close a tab using the middle mouse button  :)

**Comment by oxdc** [comment] 2024-08-12 15:30
Thank you for your feedback. If the middle click does not work, in fact, it is a bug 🐛. Sorry about this issue and I'll fix this ASAP. Personally, I only have the build-in trackpad of MacBook available and I haven't fully tested it. As a workaround right now, double click should work.

**Comment by Moyf** [comment] 2024-08-12 15:35
> Thank you for your feedback. If the middle click does not work, in fact, it is a bug 🐛. Sorry about this issue and I'll fix this ASAP. Personally, I only have the build-in trackpad of MacBook available and I haven't fully tested it. As a workaround right now, double click should work.

Hahaha roger that, thanks!

And I just found another bug 🐛 (ooops)

If I close the tab in hrer with middle mouse button, it would became like this:
![image](https://github.com/user-attachments/assets/784e2064-f2ec-4fb4-ba2b-4c1b28769225)

And even switching to other nots, it still looks like it 🤔

**Comment by Moyf** [comment] 2024-08-12 15:37
> > Thank you for your feedback. If the middle click does not work, in fact, it is a bug 🐛. Sorry about this issue and I'll fix this ASAP. Personally, I only have the build-in trackpad of MacBook available and I haven't fully tested it. As a workaround right now, double click should work.
> 
> Hahaha roger that, thanks!
> 
> And I just found another bug 🐛 (ooops)
> 
> If I close the tab in here with middle mouse button, it would became like this: ![image](https://private-user-images.githubusercontent.com/4013062/357110857-784e2064-f2ec-4fb4-ba2b-4c1b28769225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzczMDQsIm5iZiI6MTcyMzQ3NzAwNCwicGF0aCI6Ii80MDEzMDYyLzM1NzExMDg1Ny03ODRlMjA2NC1mMmVjLTRmYjQtYmEyYi00YzFiMjg3NjkyMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMTUzNjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI2MzRiNzkyNGNkYTBjYmJkMjE4MTQ0MWM2YTM1Y2Y3M2E0NGI4MDI4OWY4ZDkzY2Y4ZTFjZTgzMGM2YzQwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zIG9pjlTlGOWSKb6O5tjmx5_d8iAF1ouanFyZp82V-g)
> 
> And even switching to other notes, it still looks like it 🤔

![image](https://github.com/user-attachments/assets/87d4a887-9505-4cb3-b4b2-8c81398a74c4)

Unchecking the `Show active tabs` button would became like this ⬆️

**Comment by oxdc** [comment] 2024-08-12 15:44
Interesting, I cannot reproduce this issue. Could you please provide the debug info? You may access it by opening the Command Palette and executing "Show debug info".

**Comment by Moyf** [comment] 2024-08-13 05:29
> Interesting, I cannot reproduce this issue. Could you please provide the debug info? You may access it by opening the Command Palette and executing "Show debug info".

```
SYSTEM INFO:
	Obsidian version: v1.7.0
	Installer version: v1.5.12
	Operating system: Windows 10 Pro 10.0.22631
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 54
	Restricted mode: off
	Plugins installed: 524
	Plugins enabled: 72
		1: Dataview v0.5.67
		2: Recent Files v1.4.1
		3: QuickAdd v1.11.0
		4: Templater v2.4.1
		5: Update Time Updater v0.1.4
		6: Calendar v1.5.10
		7: Advanced URI v1.42.0
		8: Commander v0.5.1
		9: Rapid Notes v1.2.5
		10: Shell commands v0.22.0
		11: AttachFlow v0.3.1
		12: Tasks v7.7.0
		13: MySnippets v1.2.3
		14: Slash Commander v0.2.16
		15: Quick Switcher++ v4.4.0
		16: Home tab v1.2.1
		17: Latex Suite v1.9.4
		18: Settings Management v1.0.5
		19: Nuke Orphans v1.2.5
		20: Clever Search v0.2.10
		21: Front Matter Title v3.9.0
		22: Admonition v10.3.2
		23: Buttons v0.5.1
		24: Customizable Menu v2.2.0
		25: Style Settings v1.0.8
		26: Periodic Notes v0.0.17
		27: Soomda v1.0.4
		28: Daily Note Navbar v0.2.0
		29: Note Toolbar v1.9.12
		30: Hotkeys for templates v1.4.3
		31: Reveal Active File Button v2.0.3
		32: Folder notes v1.7.26
		33: File Explorer++ v1.2.1
		34: Workspaces Plus v0.3.3
		35: Image Toolkit v1.4.1
		36: Code Editor Shortcuts v1.14.0
		37: Task List Kanban v1.2.5
		38: Plugins Annotations v1.4.0
		39: Easy Typing v5.5.0
		40: Heading Shifter v1.5.1
		41: Open vault in VSCode v1.2.3
		42: Creases v0.7.0
		43: Components v1.6.0
		44: Sort & Permute lines v0.7.0
		45: View Count v2.4.1
		46: Datepicker v0.3.23
		47: AI image analyzer v0.1.10
		48: Local GPT v1.8.1
		49: BMO Chatbot v2.3.3
		50: Repeat Last Command(s) v2.10.0
		51: Dashboard navigator v1.1.1
		52: No dupe leaves v0.0.12
		53: GDScript Syntax Highlighting v1.0.3
		54: Optimize Canvas Connections v1.0.0
		55: Advanced Canvas v3.1.0
		56: Node Auto Resize v1.0.1
		57: Outliner.md v0.1.8
		58: Dynamic Highlights v0.3.1
		59: Set View Mode per Note v1.0.3
		60: Pane Relief v0.5.4
		61: Attachment Pro v0.1.0
		62: Hover Editor v0.11.20
		63: Strange New Worlds v2.1.4
		64: ManicTime v1.0.0
		65: Linter v1.25.0
		66: Pomodoro Timer v1.2.3
		67: Code Styler v1.1.7
		68: WuCai highlights Official v24.8.9
		69: Tabs v1.1.7
		70: Vault Explorer v1.41.0
		71: Emoji Autocomplete v1.4.1
		72: Html Server v1.0.8

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

I may have enabled too many plugins, haha..

**Comment by oxdc** [comment] 2024-08-13 07:46
From the debug report, as no community theme is enabled, probably one of the 54 CSS snippets has some incompatible properties.

Could you please try to reproduce the same issue in Sandbox vault? You can see it by clicking the help button. After opening the Sandbox vault, enable community plugins and install only *Vertical Tabs*.

If it works fine in the Sandbox, you may try disabling half of the snippets or plugins each time to find the incompatible one.

**Comment by Moyf** [comment] 2024-08-13 09:27
> From the debug report, as no community theme is enabled, probably one of the 54 CSS snippets has some incompatible properties.
> 
> Could you please try to reproduce the same issue in Sandbox vault? You can see it by clicking the help button. After opening the Sandbox vault, enable community plugins and install only _Vertical Tabs_.
> 
> If it works fine in the Sandbox, you may try disabling half of the snippets or plugins each time to find the incompatible one. As a reminder, since you have too many snippets and plugins, before testing, **please make sure you have a full backup, including all the files in your vault and a list showing which of these customizations are enabled.**

I tried it in sandbox and it works with no problem!
And later I tried in my vault, too. And the bug appeared once, then after resizing my window, it fixed.
So I think I'll try to reproduce it and to see what might conflict with it!

**Comment by oxdc** [comment] 2024-08-13 15:26
Thank you for your feedback. It appears that this issue is not directly caused by *Vertical Tabs*.

Some suggestions:
It is advisable to reopen Obsidian after updating plugins or themes. Sometimes, it would be helpful to regularly reinstall Obsidian with newly downloaded installer (uninstallation is _not_ required), which would update the electron.js engine, not only the JavaScript code bundles.

**Comment by Moyf** [comment] 2024-08-13 15:39
> Thank you for your feedback. It appears that this issue is not directly caused by _Vertical Tabs_.
> 
> If you are able to pinpoint the exact cause of this incompatibility, I can publish a hot fix.
> 
> Some suggestions: It is advisable to reopen Obsidian after updating plugins or themes. Sometimes, it would be helpful to regularly reinstall Obsidian with newly downloaded installer (uninstallation is _not_ required), which would update the electron.js engine, not only the JavaScript code bundles.

I understand, thank you very much for your patient explanation!

**Comment by oxdc** [comment] 2024-08-14 10:59
This middle click issue should be resolved. Could you please update and test it? If it doesn't work, please reopen this issue. If you discover CSS issues that can be reproduced in Sandbox Vault, please open a new issue. Thanks for your support!

**Comment by Moyf** [comment] 2024-08-15 16:49
> This middle click issue should be resolved. Could you please update and test it? If it doesn't work, please reopen this issue. If you discover CSS issues that can be reproduced in Sandbox Vault, please open a new issue. Thanks for your support!

Sorry for the late reply! I have updated and tested, and the middle mouse button function is working fine! Thank you! 
(As for that CSS issue, I haven't found a stable way to reproduce it yet.)

**Comment by Elaws** [comment] 2024-09-08 21:51
Same issue here. No CSS snipet, no custom theme. Middle click just triggers the "scroll" mode instead of closing the tab. Middle click does close tab if Vertical Tabs plugin is disabled.

Please find here the debug info :

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 11 Home 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Color_Headers
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 41
	Plugins enabled: 35
		1: Templater v2.1.4
		2: Paste URL into selection v1.7.0
		3: QuickAdd v1.6.1
		4: Shortcuts extender v2.2.0
		5: Periodic Notes v0.0.17
		6: Quick Latex v2.6.5
		7: Natural Language Dates v0.6.2
		8: Mind Map v1.1.0
		9: MetaEdit v1.8.2
		10: Maximise Active Pane v0.0.3
		11: Latex Environments v0.4.2
		12: Kanban v1.5.3
		13: Calendar v1.5.10
		14: Citations v0.4.5
		15: Dataview v0.5.64
		16: Day Planner v0.16.0
		17: Emoji Toolbar v0.4.1
		18: Excalidraw v2.0.20
		19: Extended MathJax v0.4.1
		20: Wrap with shortcuts v1.3.0
		21: Custom window title v0.3.5
		22: BibNotes Formatter v0.9.214
		23: Sort & Permute lines v0.7.0
		24: Quick Switcher++ v4.0.0
		25: Advanced Mobile Toolbar v1.8.0
		26: Custom Attachment (Modified) v0.0.6
		27: Image Captions v1.1.0
		28: Hotkey Helper v0.3.18
		29: Outliner v4.8.0
		30: Admonition v10.1.2
		31: Completr v3.2.0
		32: Vertical Tabs v0.6.8
		33: BRAT v0.8.4
		34: Hotkeys++ v0.2.7
		35: Media Extended v2.11.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Comment by oxdc** [comment] 2024-09-09 08:02
@Elaws May I ask if you could reproduce the problem in the Sandbox Vault?

**Comment by Elaws** [comment] 2024-09-14 17:47
@oxdc Thanks for your reply. Well, I can't figure out what has happened, but I'm unable to reproduce the issue I had the other day... 

Will update here if needed !

**Comment by N3C2L** [comment] 2024-09-18 20:42
@oxdc 
I think I have found a source of the problem for why closing tabs with the middle mouse button sometimes doesn't work.

Steps:
1. Open a sandbox vault
2. Open many new tabs with .md files in a single left tab group
3. Open so many files, that the vertical tabs interface shows scrollbars on the right side
4. Try to close a tab with the middle mouse button
5. Result is, that the autoscroll of the mouse will get activated. This is not happening when there are no scrollbars visible (less tabs). It's what @Elaws mentioned above too: "Middle click just triggers the "scroll" mode instead of closing the tab."

**Comment by oxdc** [comment] 2024-09-19 04:25
@N3C2L Thank you for providing the details! I will try to fix this issue.

**Closed** 2024-09-27 11:44 UTC
Labels: bug

**Comment by oxdc** [comment] 2024-09-27 12:58
> 5\. the autoscroll of the mouse will get activated

This issue should be fixed now. Please update ASAP. Thank you guys for reporting and helping me find the cause. 🎉
