### ISSUE TITLE
Compatibility: Ctrl + Mousewheel zooming in Markmind extension's Mindmap does not work with Vertical Tabs plugin enabled 

### ISSUE THREAD

**Issue by piotrnajda3000** [oxdc/obsidian-vertical-tabs#86] opened 2024-12-22 10:42 UTC
### Bug Report Checklist

- [X] I have searched existing issues and this is not a duplicate
- [X] I have updated to the latest version of Vertical Tabs
- [X] I have disabled all other plugins and themes to ensure the issue is with Vertical Tabs
- [X] I have restarted Obsidian after disabling other plugins and themes, and the issue persists

### Environment (Optional)

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] iPadOS

### Bug Description

- Expected: I can zoom out of my Markmind mindmap using Ctrl + Mousewheel gesture, while Vertical Tabs plugin is enabled
- Actual: I can't  

### Steps to Reproduce

1. Install the Markmind extension (It has 330k downloads, so quite popular) 
2. Create a new Mindmap using command `Markmind: Create new Mindmap` 
3. Try to zoom in/out using Ctrl + Mousewheel 

### Debug Information

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: #49~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov  6 17:42:15 UTC 2 6.8.0-49-generic
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Markmind v3.0.9
		2: Vertical Tabs v0.12.4

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

NOTE: I verified the same issue exists in v1.7.7 - I'm using 1.6.7, since performance took a critical hit when I updated to 1.7.7. 

### Can you reproduce the bug in the "Sandbox vault"? Please skip this for mobile platforms by selecting "Not applicable".

Yes

### Screenshots (Optional)

https://github.com/user-attachments/assets/443ac344-7195-47be-b07d-455f4668a757

I can't zoom in/out given the Vertical Tabs plugin enabled. I reloaded the app so that it becomes clear the issue is with the plugin enabled. 

### Additional Information (Optional)

This might be an issue with Markmind, since I don't have problems zooming in/out of a Canvas. 

I will try and investigate the issue later, when I have some time :) I realize this might be a niche bug. 

Thank you for the plugin, it's interesting seeing something Sidebery-esque come alive into Obsidian 👀

**Comment by oxdc** [comment] 2024-12-23 04:26
Hi @piotrnajda3000 ! I’ve confirmed this is a bug in Markmind, and I’ve fixed it locally on my computer. However, since the issue is unrelated to Vertical Tabs and Markmind is closed-source, I’m unable to make changes or submit a pull request. I recommend reporting this issue on their repository. I'll close this issue now.

The problem lies in Markmind binding the `mousewheel` event to `document.body`, which stops firing correctly after the React runtime loads. Moreover, the practice of binding `mousewheel` to the root element is poorly designed and not recommended in the first place.

To fix the issue, the following changes should be made on their side:

In the `initEvent` function:

```diff
-  this.doc.body.addEventListener("mousewheel", this.appMousewheel),
+  this.appEl.addEventListener("mousewheel", this.appMousewheel),
```

In the `removeEvent` function:

```diff
-  this.doc.body.removeEventListener("mousewheel", this.appMousewheel),
+  this.appEl.removeEventListener("mousewheel", this.appMousewheel),
```

Optional, but recommended improvements:

1. Use the `{ passive: true }` option for better performance:

In the `initEvent` function:

```diff
-  this.doc.body.addEventListener("mousewheel", this.appMousewheel),
+  this.appEl.addEventListener("mousewheel", this.appMousewheel, { passive: true }),
```

2. Avoid unnecessary calls to `preventDefault()`:

In the `appMousewheel` function:

```diff
  appMousewheel(t) {
    if (!this.isRead) {
      var e,
        i = t.ctrlKey || t.metaKey;
      t.wheelDelta ? (e = t.wheelDelta / 120) : t.detail && (e = -t.detail / 3),
        e &&
          (e < 0
            ? i &&
-              (t.preventDefault(), t.stopPropagation(), this.setScale("down"))
+              (t.stopPropagation(), this.setScale("down"))
            : i &&
-              (t.preventDefault(), t.stopPropagation(), this.setScale("up")));
+              (t.stopPropagation(), this.setScale("up")));
    }
  }
```

These adjustments should resolve the issue. Please let the maintainers of Markmind know. Thank you!

**Closed by oxdc** 2024-12-23 04:26 UTC
Labels: bug
