### ISSUE TITLE
[Bug]File list renaming and searching lost focus

### ISSUE THREAD

**Issue by bakebakebakebake** [oxdc/obsidian-vertical-tabs#83] opened 2024-12-17 07:46 UTC
**Describe the bug**
File list renaming and searching lost focus

**To Reproduce**
Rename files in the file list and search in the search box.

**Expected behavior**
The expected behavior is that I can rename files in the file list without affecting the search function.

**Screenshots**

https://github.com/user-attachments/assets/56025eac-7cd7-4a09-8fe7-dc2e6c57b10a

https://github.com/user-attachments/assets/d06bb2a5-7c4d-4993-9b29-50a28ca555e8

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version 1.7.7

**Additional context**
If I disable this plugin, everything returns to normal, but the issue occurs when it is enabled.

**Comment by oxdc** [comment] 2024-12-17 07:58
Hi @bakebakebakebake ! This bug should be fixed in v0.12.3. Have you updated to the latest version?

**Comment by oxdc** [comment] 2024-12-17 07:59
Duplicate of #77

**Closed** 2024-12-17 08:14 UTC
Labels: bug
